emo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth.views import login
from django.views.generic.base import TemplateView
from management import views
from django.contrib.auth.decorators import login_required

from tastypie.api import Api
from api.api.resources import StatusResource, SlowControlResource, RunsResource, QualityResource
daqapi = Api(api_name="daq")
daqapi.register(StatusResource())
scapi = Api(api_name="history")
scapi.register(SlowControlResource())
runapi = Api(api_name="runs")
runapi.register(RunsResource())
qualityapi = Api(api_name="ui")
qualityapi.register(QualityResource())

urlpatterns = [
 
    url(r'^$', TemplateView.as_view( template_name='base.html')),
    url(r'^test', TemplateView.as_view( template_name='base_test.html')),
    url(r'^game', login_required(TemplateView.as_view( template_name='game.html'))),
#    url(r'^pong', login_required(TemplateView.as_view( template_name='pong.html'))),
    url(r'^eatitlux/', include(admin.site.urls)),
    url(r'^pong', include('pong.urls')),                                              
    url(r'^april', TemplateView.as_view(template_name='base_april.html')),
    url(r'^fancy', TemplateView.as_view(template_name='base_fancy.html')),
    #url(r'^get_login/', views.get_login, name='get_login'),
    #url(r'^accounts/login',login(template_name="login.html"),name="login"),
#    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
 #       kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout', views.logout_page,name='logout'), #must add
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^supermanrequest', views.getStartingUser, name='getstartinguser'),
    url(r'^get_user_doc/', views.get_user_doc, name='get_user_doc'),

    # Documentation
    url(r'^management/', include('management.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^runs/', include('runs.urls')),
    url(r'^control/', include('control.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^access/', include('access_log.urls')),
    url(r'^slow_control/', include('slow_control.urls')),
    url(r'^equipment/', include('equipment.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^api/', include(daqapi.urls)),
    url(r'^sc_api/', include(scapi.urls)),
    url(r'^runs_api/',include(runapi.urls)),
    url(r'^qapi/', include(qualityapi.urls)),
    url(r'^online_monitor/', include('online_monitor.urls')),
    
]

management/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from management import views

urlpatterns = [

    url(r'^update_user', views.update_user, name='update_user'),
    url(r'^shift_rules', views.shift_rules, name='shift_rules'),
    url(r'^shift_calendar', views.shift_calendar, name="shift_calendar"),
    url(r'^get_user_list', views.get_user_list, name='get_user_list'),
    #url(r'^shift_management', views.shift_management, name='shift_management'),
    url(r'^get_current_shifter', views.GetCurrentShifter, name='get_current_shifter'),
    url(r'^get_shift_stats', views.GetShiftStats, name='get_shift_stats'),
    url(r'^get_shifts', views.GetShifts, name='get_shifts'),
    url(r'^shift_history', views.ShiftHistory, name="shift_history"),
    url(r'^get_hs', views.GetHs, name="get_hs"),
    url(r'^set_hs', views.SetHs, name="set_hs"),
    url(r'$', login_required(views.get_user_list), name="user_management")
]

management/models.py
from django.db import models
from django import forms
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField( User, related_name="profile" )
    control_permission_date = models.DateTimeField(null = True, default = datetime.datetime.min )
    last_login = models.DateTimeField(null=True, default=datetime.datetime.min)
    #db_profile_complete = models.BooleanField(default=False)
    def canstartruns(self):
        if (datetime.datetime.now( datetime.timezone.utc ) - self.control_permission_date).days < 7:
            return True
        return False

weekdays = ( ("Monday", "Monday"),
             ("Tuesday", "Tuesday"),
             ("Wednesday", "Wednesday"),
             ("Thursday", "Thursday"),
             ("Friday", "Friday"),
             ("Saturday", "Saturday"),
             ("Sunday", "Sunday") )
years = (( "2016", "2016"),
         ( "2017", "2017"),
         ( "2018", "2018"),
         ( "2019", "2019"),
         ( "2020", "2020"),
         ( "2021", "2021"),
         ( "2022", "2022"),
         ( "2023", "2023"),
         ( "2024", "2024"),
         ( "2025", "2025"),
         ( "2026", "2026"))
shift_types = (("responsible", "responsible"), ("shifter", "shifter"),
               ("training", "training"), ("run coordinator", "run coordinator"), ("credit", "credit"))
class ShiftDefinition(forms.Form):
    year = forms.ChoiceField(choices=years, required=True, label="Year valid", 
                             help_text="Only one rules definition allowed per year")
    shifts_per_week = forms.IntegerField(required=True, label="Shifts per week", 
                                         help_text="Number of people that must be on site each week")
    start_date = forms.DateField(label="Start date", initial=datetime.date.today,
                                 help_text="When the shift definition goes into effect.")   
    collab_def_data = forms.DateField(label="Collaboration count date", 
                                      initial=datetime.date.today, help_text="When the collaboration list is read to determine this period's responsibility")
    auto_assign_weeks = forms.IntegerField(label="Auto assign weeks", help_text="How many weeks ahead the program should auto-assign in case of unclaimed shifts.")
    shift_reset = forms.ChoiceField(choices=weekdays, required=True, 
                                    label="Shift start/end", help_text="The day of the week shifts start/end")    
    auto_assign_start = forms.DateField(label="Auto assignment from", help_text="The date that shift autoassignments start. Can be the same as the start date.")    

class ShiftSignUp(forms.Form):

    class ChoiceFieldNoValidation(forms.ChoiceField):
        def validate(self, value):
            pass

    start_date = forms.DateField(required=True, label="Shift start", 
                                 help_text="First day of shift")
    end_date = forms.DateField(required=True, label="Shift end",
                               help_text="Last day of shift")
    user = ChoiceFieldNoValidation(required=True, label="User", help_text="Username")
    shift_type = ChoiceFieldNoValidation(required=True, help_text="Type of shift")
    institute = ChoiceFieldNoValidation(required=True, label="Affiliation")
    has_car = forms.BooleanField(required=False,label="Do you have a car?", 
                                 help_text="Check if you will have access to a car")
    comment=forms.CharField(required=False, max_length=1000, label="Comment", 
                            help_text="(optional) put here any special things you would like noted")
    remove = forms.BooleanField(required=False, widget=forms.HiddenInput)
class UserInfo(forms.Form):
    username = forms.CharField(required=True, max_length=250)
    last_name = forms.CharField(required=True, label="Family name", max_length=200)
    first_name = forms.CharField(required=True, label="First name(s)", max_length=250)
    institute = forms.ChoiceField(choices=settings.INSTITUTES,required=True, label='Affiliation')
    position=forms.ChoiceField(choices=settings.JOBS, required=True,label="Position")
    email = forms.CharField(max_length=250, label="Email", required=True)
    skype_id = forms.CharField(max_length=200, label="Skype name", required=False)
    github_id = forms.CharField(max_length=200, label="Github name", required=False)
    cell = forms.CharField(max_length=200, label="Cell number", required=False)
    nickname = forms.CharField(max_length=250, label="Preferred nickname", required=False)
    start_date = forms.DateField(label="Start date", required=False, 
                                 help_text="Date that person started in XENON")
    end_date = forms.DateField(label="End date", required=False,
                               help_text="Date that person left XENON (empty if none)")
class UserRequest(forms.Form):
    auth = forms.CharField(max_length=10)

management/templates/management/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
{% load staticfiles %}

<div style="padding:15px;padding-bottom:5px">
    <div class="row">
      <div class="col-sm-8 col-xs-12" style="padding:10px;background-color:white;border-color:#AAAAAA;border-width:1px;border-style:solid;height:250px;font-size:medium;padding-top:10px">
	<div class="row">
	  <div class="col-xs-6"><h3>User information for {{ user.username }}</h3></div>
	  <div class="pull-right">
	    <button class="btn btn-info" onclick="UserFormModal()" style="margin-right:30px;">Update info</button>
	  </div>
	</div>
	<div class="row">
	  <div class="col-xs-3"><strong>Name:</strong></div>
	  <div class="col-xs-9">{{ mdb.first_name }} {{ mdb.last_name }}</div>
	</div>
	<div class="row">
          <div class="col-xs-3"><strong>Institute:</strong></div>
          <div class="col-xs-9">{{ mdb.institute }}</div>
        </div>
<div class="row">
          <div class="col-xs-3"><strong>Position:</strong></div>
          <div class="col-xs-9">{{ mdb.position }}</div>
        </div>
<div class="row">
          <div class="col-xs-3"><strong>Email:</strong></div>
          <div class="col-xs-9">{{ mdb.email }}</div>
        </div>
<div class="row">
          <div class="col-xs-3"><strong>Skype ID:</strong></div>
          <div class="col-xs-9">{{ mdb.skype_id }}</div>
        </div>
<div class="row">
          <div class="col-xs-3"><strong>Github ID</strong></div>
          <div class="col-xs-9">{{ mdb.github_id }}</div>
        </div>
       <div class="row">
          <div class="col-xs-3"><strong>Phone:</strong></div>
          <div class="col-xs-9">{{ mdb.cell }}</div>
        </div>
<div class="row">
          <div class="col-xs-3"><strong>Nickname:</strong></div>
          <div class="col-xs-9">{{ mdb.nickname }}</div>
        </div>

      </div>
      <div class="col-sm-4 col-xs-12" style="padding:10px;background-color:white;border-color:#AAAAAA;border-width:1px;border-style:solid;height:250px;">
	<div class="col-xs-12"><h3>Permissions</h3><br></div>
	
	<div style="padding-left:60px">
	  {% if user.is_authenticated %}
	  <li> You <strong>may</strong> post new log messages</li>
	  <li> You <strong>may</strong> view the run history</li>
	  <li> You <strong>may</strong> view the acquisition status and control panels</li>
	  {% if canstartruns %}
	  <li> You <strong>may</strong> start and stop data taking until {{ expiration|date:"D d M Y" }}</li>
	  {% else %}       
	  <li> You <strong>may not</strong> start and stop data taking
	    {% endif %}
	    {% if user.is_superuser %}
	  <li> You <strong>may</strong> create new operations modes</li>
	  {% else %}
	  <li> You <strong>may not</strong> create new operations mode</li>
	  {% endif %}
	  {% if user.is_superuser %}
	  <li> You <strong>may</strong> access the admin interface (if you know how)</li>
	  {% else %}
	  <li> You <strong>may not</strong> access the admin interface</li>
	  {% endif %}
	  {% else %}
	  <li> You may view the homepage and a few other pages, but no content pages. Please log in to access the full site.</li>
	  {% endif %}
	</div>
      </div>
    </div>
</div>

<div class="bg" style="padding:10px;width:100%;background-color:white;border-color:#AAAAAA;border-width:1px;border-style:solid;">
  <h3> DAQ Control Authorization Request </h3>
<br>
  <p>
    <strong>Brief:</strong> Only one user may have "DAQ Controller" status at once. This is to avoid sending conflicting commands
    to the DAQ from multiple sessions and also to avoid accidental DAQ control. All functions are available to non-controller
    users except Start/Stop of data acquisition (also certain configuration functions are reserved for admins). If you
    are the shifter and you need to start and stop runs you may 'steal' the controller status from the current controller via this form.
  </p>
  <p>
    <strong>Note:</strong> All control actions are logged.
  </p>
  <p>
    <strong>Further note:</strong> If you want to relinquish your controller status you can do that here as well. It will expire
    automatically after one week and must be renewed here.</p>
  <br>
  <form action="/profile/" method="post" style="padding-left: 50px">
    {% csrf_token %}
    <button class="btn btn-success" type=submit value="auth" name="auth">I am a responsible person, give me the power</button>
    <button class="btn btn-danger" type=submit value="unauth" name="auth">Remove my shifter permissions</button>
  </form>
  <br>
</div>

<div class="modal fade" id="userUpdateModal" style="width:100%">
  <div class="modal-dialog">
    <div class="modal-content" style="height:100%">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal" aria-hidden="true">×
        </button>
        <h4 class="modal-title" id="new_eq_title">Update Profile
        </h4>
      </div>
      <div class="modal-body" style="min-height:200px;overflow-y:auto;height:80%">
	<form action="/profile/" method="post">
	  {% csrf_token %}
	  {{ form.non_field_errors }}
	  <input type="hidden" id="id_username" value="{{user.get_username}}" name="username"/>
	  <div class="row">
	    {{ form.last_name.errors }}
	    <div class="col-xs-3"><strong>Last name*:</strong></div>	  
	    <div class="col-xs-9">{{ form.last_name }}</div>
	  </div>
	  <div class="row">
            {{ form.first_name.errors }}
            <div class="col-xs-3"><strong>First name*:</strong></div>
            <div class="col-xs-9">{{ form.first_name }}</div>
          </div>
	  <div class="row">
            {{ form.institute.errors }}
            <div class="col-xs-3"><strong>Institute*:</strong></div>
            <div class="col-xs-9">{{ form.institute }}</div>
          </div>
	  <div class="row">
            {{ form.position.errors }}
            <div class="col-xs-3"><strong>Position*:</strong></div>
            <div class="col-xs-9">{{ form.position }}</div>
          </div>
	  <div class="row">
            {{ form.email.errors }}
            <div class="col-xs-3"><strong>Email*:</strong></div>
            <div class="col-xs-9">{{ form.email }}</div>
          </div>
	  <div class="row">
            {{ form.skype_id.errors }}
            <div class="col-xs-3"><strong>Skype name:</strong></div>
            <div class="col-xs-9">{{ form.skype_id }}</div>
          </div>
	  <div class="row">
            {{ form.github_id.errors }}
            <div class="col-xs-3"><strong>Github name:</strong></div>
            <div class="col-xs-9">{{ form.github_id }}</div>
          </div>
	  <div class="row">
            {{ form.cell.errors }}
            <div class="col-xs-3"><strong>Cell Phone:</strong></div>
            <div class="col-xs-9">{{ form.cell }}</div>
          </div>
	  <div class="row">
            {{ form.nickname.errors }}
            <div class="col-xs-3"><strong>Preferred name:</strong></div>
            <div class="col-xs-9">{{ form.nickname }}</div>
          </div>
	  <p><input class="btn btn-info" type="submit" value="Update" /></p>
	</form>
      </div>
      <hr>
    </div>
  </div>
</div>

<script>
function UserFormModal(){
$('#userUpdateModal').modal('show');
$("#id_last_name").val("{{mdb.last_name}}");
$("#id_first_name").val("{{mdb.first_name}}");
$("#id_institute").val("{{mdb.institute}}");
$("#id_position").val("{{mdb.position}}");
$("#id_email").val("{{mdb.email}}");
$("#id_skype_id").val("{{mdb.skype_id}}");
$("#id_github_id").val("{{mdb.github_id}}");
$("#id_cell").val("{{mdb.cell}}");
$("#id_nickname").val("{{mdb.nickname}}");

//document.getElementById("id_first_name").innerHTML="{{mdb.first_name}}";
}
</script>

{% endblock %}

management/templates/management/shift_calendar.html
{% extends "base.html" %}
{% block title %}Shift Calendar{% endblock %}
{% load staticfiles %}
{% block head %}
<script src="{% static "js/moment.js"%}"></script>
<!--<script src="{% static "Dygraph/js/dygraph-combined.js"%}"></script>-->
<script src="{% static "plotly_20150819a_basic/dependencies/d3.v3.min.js" %}"></script>
 <script src="{% static "js/plotly-latest.min.js" %}"></script>
<script src="{% static "js/fullcalendar.min.js"%}"></script>
<link href="{% static "css/fullcalendar.min.css"%}" rel="stylesheet" />
<!--<script src="{% static "js/fullcalendar_weekList.js"%}"></script>
<link href="{% static "css/fullcalendar_weekList.css"%}" rel="stylesheet" />-->

<script src="{% static "emo/js/shift_calendar.js"%}"></script>

<style>
.calbox{
    background-color: white;
    border-width: 1px;
    border-color: #D5D5D5; /*#5992c2w;*/
    border-style: solid;
    #width:100%;
    min-height:500px;
    margin-top: 5px;
    margin-bottom: 5px;
    /*box-shadow: 10px 10px 5px #888888;*/
    padding-top:10px;
}
.fc-event{
    cursor: pointer;
}
.cal_ul {
    display:inline;
    list-style: none;
    padding:0;
    margin:0;
}

.cal_li { 
    padding-left: 1em; 
    text-indent: -.7em;
    display:inline;
}

#ttip {
box-shadow: 10px 10px 5px #888888;
    z-index: 10;
    min-width:300px;
    min-height:100px;
//    position:relative;
    display: none;
    position:fixed;
    background-color:white;
    padding:10px;    
//    visibility: invisible;
}
.assigned:before {
    content: "■ ";
    font-size:x-large;
    color: #5992c2; /* or whatever color you prefer */
}
.free:before {
    content: "■ ";
    font-size:x-large;
    color: #36bc98; /* or whatever color you prefer */
}
.run_coordinator:before {
    content: "■ ";
    font-size:x-large;
    color: #5a54bd; /* or whatever color you prefer */
}
.training:before{
    content: "■ ";
    font-size:x-large;
    color: #ffa500; /* or whatever color you prefer */
}

</style>
<script type="text/javascript">


function CloseTooltip(){
$(".ttip").css('display', 'none');//removeClass("show");
}
//var colors = {"tpc": "#36bc98", "muon_veto": "#5a54bd", "combined": "#5992c2"};
function componentToHex(c) {
    var hex = c.toString(16);
    return hex.length == 1 ? "0" + hex : hex;
}
function rgbToHex(r, g, b) {
    return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
}


function UpdateUserList(){
   var user_options = {{user_list|safe}};
   var value = $("#id_institute").val();
   
   ret="";
console.log(user_options);
console.log(value);
   for(var key in user_options){
     if(key == value){
        for(i=0;i<user_options[key].length;i+=1){
            ret += "<option value='"+user_options[key][i]['username']+"'>"+
    user_options[key][i]['username'] + " (" +user_options[key][i]['first_name']+" "+user_options[key][i]['last_name']+")</option>";
        }
}}
   document.getElementById("id_user").innerHTML=ret;
};

$(document).ready(function() {
		    
$("#id_institute").change(function(){
   UpdateUserList();
});

   user_option = {{ user_list |safe }};

   MakeCalendar("calendar", user_option);

  ret="";
  for (var key in user_option) {
  if (user_option.hasOwnProperty(key)) {
     ret+="<option value='"+key+"'>"+key+"</option>";
    }
  }
  document.getElementById("id_institute").innerHTML = ret;
  UpdateUserList();
});


</script>
{% endblock %}
{% block content %}

<div class="row" style="padding:14px;padding-top:0px;">
  <div class="calbox col-sm-8 col-xs-12" style="min-width:400px;">
    <ul class="cal_ul" id="calendar-legend" class="pull-right">
      <li class="cal_li assigned">Assigned</li>
      <li class="cal_li free">Free</li>
      <li class="cal_li run_coordinator">Run Coordinator</li>
    </ul>
    <div id="calendar"></div>     
  </div>           
  <div class="calbox col-sm-4 col-xs-12" style="padding:0;display:none">
    <div class="col-xs-12" id="sidebar">
      <h4>Institutes</h4>
      <table class="table table-condensed">
	<thead>
	  <tr>
	    <td>Institute</td>
	    <td>Rollover</td>
	    <td id="current_year_column">Shifts</td>
	  </tr>
	</thead>
	<tbody id="inst_table_body">
	</tbody>
      </table>
    </div>
  </div>
</div>

<div class="ttip" id="ttip" 
     style="width:450px;border-width:1px;border-color:#BBBBBB;border-style:solid;">
  <div class="row" style="width:400px;margin-left:10px;">
    <button type="button" class="close"
            onclick="CloseTooltip()" aria-hidden="true">×</button>
    <h4 class="modal-title" id="shift_modal_title">Shift detail</h4>
  </div>
  <hr style="margin:2px">
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <strong>Start: </strong>
    </div>
    <div class="col-xs-8 col-sm-3">
      <span id="shift_modal_start"></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <strong>End: </strong>
    </div>
    <div class="col-xs-8 col-sm-3">
      <span id="shift_modal_end"></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <strong>Institute: </strong>
    </div>
    <div class="col-xs-8 col-sm-3">
      <span id="shift_modal_institute"></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <strong>User: </strong>
    </div>
    <div class="col-xs-8 col-sm-3">
      <span id="shift_modal_user"></span>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <strong>Available: </strong>
    </div>
    <div class="col-xs-8 col-sm-3">
      <span id="shift_modal_available"></span>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12">
      <button class="btn btn-info" id="btn_sign_up">Sign up</button>&nbsp;<button class="btn btn-default" id="btn_mark_available">Mark Available</button>&nbsp;<button class="btn btn-warning" id="btn_train">Sign up for training</button>
      {% if request.user.username == 'coderre' or request.user.username == 'junji' %}
      <button class="btn btn-warning" id="btn_credit">Make credit shift</button>
      {% endif %}
    </div>
  </div>
</div>


<div class="modal fade" id="signUpModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal" aria-hidden="true">×
        </button>
        <h4 class="modal-title" id="sign_up_title">Sign up for a shift</h4>
      </div>
      <span style="font-size:12px;margin-left:15px;" id="sign_up_start">Shift start</span>
      <span style="font-size:12px;margin-left:15px;"><strong>* required field</strong></span>
      <form method="POST" action="/management/shift_calendar" id="sign_up_form">
        {% csrf_token %}
	<div class="modal-body" style="min-height:200px;overflow-y:auto;">
	  <div class="bg-danger">
	    <strong>Note: </strong> Shifts start on Wednesday at the operations telecon and end the following Wednesday <strong>after</strong> the operations telecon. Plan your travel accordingly.
	    </div>
	  <br>
	  {% load tz %}
	  {% localtime off %}

	  {{ signup_form.non_field_errors }}
          {% for field in signup_form.visible_fields %}
          <div class="row">
            <div class="col-sm-6"><strong>{{ field.label }}{% if field.field.required %}*{% endif %}</strong></div>
            <div class="col-sm-6">{{ field }}</div>
	    {{ field.errors }}
          </div>
          <br style="margin:1px">
          {% endfor %}
	  {% for field in signup_form.hidden_fields %}
	  {{field}}
	  {% endfor %}
	  {% endlocaltime %}


        </div>
        <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn btn-danger">Cancel</a>
          <button type="submit" class="btn btn-success">
            Enter</button>
        </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

management/templates/management/shift_rules.html
{% extends "base.html" %}
{% block title %}Shift Management{% endblock %}
{% load staticfiles %}
{% block head %}
{% endblock %}
{% block content %}
<div class="emobox" style="padding:10px;overflow:hidden">
  <h3>Shift Responsibility <span id="resp_year">{{ year }}</span> (total: {{resp.total}} weeks)</h3>
  <br>
   {% for key, value in resp.shifts.items %}
  <div class="col-sm-6 col-xs-12"><strong>{{ key }}: </strong>{{ value.shifts|floatformat:2 }} weeks, {{ value.people }} people (frac: {{ value.frac|floatformat:2 }})</div>
  {% endfor %}
</div>
{% if user.username == "coderre" %}
<div class="emobox" style="padding:10px">
<h3>Shift rules</h3>
<p style="color:red">
  This form no longer works!
</p>
<form method="POST" action="/management/shift_rules">
{% csrf_token %}
{% for field in form %}
<div class="row">
  <div class="col-xs-3">
    <strong>{{ field.label }}:</strong>
  </div> 
  <div class="col-xs-3">
    {{ field }}
  </div>
  <div class="col-xs-6">
  <span style="color:#999999">{{ field.help_text }}</span>
  </div>
</div>
<hr>
{% endfor %}

<button class="btn btn-info btn-sm disabled" style="margin:8px;" type="submit" name="submit" style="height:30%;">Submit</button>
{% endif %}

</form>
<script>
console.log({{resp}});
</script>
</div>

{% endblock %}