emo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth.views import login
from django.views.generic.base import TemplateView
from management import views
from django.contrib.auth.decorators import login_required

from tastypie.api import Api
from api.api.resources import StatusResource, SlowControlResource, RunsResource, QualityResource
daqapi = Api(api_name="daq")
daqapi.register(StatusResource())
scapi = Api(api_name="history")
scapi.register(SlowControlResource())
runapi = Api(api_name="runs")
runapi.register(RunsResource())
qualityapi = Api(api_name="ui")
qualityapi.register(QualityResource())

urlpatterns = [
 
    url(r'^$', TemplateView.as_view( template_name='base.html')),
    url(r'^test', TemplateView.as_view( template_name='base_test.html')),
    url(r'^game', login_required(TemplateView.as_view( template_name='game.html'))),
#    url(r'^pong', login_required(TemplateView.as_view( template_name='pong.html'))),
    url(r'^eatitlux/', include(admin.site.urls)),
    url(r'^pong', include('pong.urls')),                                              
    url(r'^april', TemplateView.as_view(template_name='base_april.html')),
    url(r'^fancy', TemplateView.as_view(template_name='base_fancy.html')),
    #url(r'^get_login/', views.get_login, name='get_login'),
    #url(r'^accounts/login',login(template_name="login.html"),name="login"),
#    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
 #       kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout', views.logout_page,name='logout'), #must add
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^supermanrequest', views.getStartingUser, name='getstartinguser'),
    url(r'^get_user_doc/', views.get_user_doc, name='get_user_doc'),

    # Documentation
    url(r'^management/', include('management.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^runs/', include('runs.urls')),
    url(r'^control/', include('control.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^access/', include('access_log.urls')),
    url(r'^slow_control/', include('slow_control.urls')),
    url(r'^equipment/', include('equipment.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^api/', include(daqapi.urls)),
    url(r'^sc_api/', include(scapi.urls)),
    url(r'^runs_api/',include(runapi.urls)),
    url(r'^qapi/', include(qualityapi.urls)),
    url(r'^online_monitor/', include('online_monitor.urls')),
    
]

log/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from log import views

urlpatterns = [

    url(r'^new_comment', views.new_comment, name='new_comment'),
    url(r'^new_log_entry', views.new_log_entry, name='new_log_entry'),
    url(r'^get_dispatcher_log', views.get_dispatcher_log, name='get_dispatcher_log'),
    url(r'^getstatus', views.get_status, name='get_status'),
    url(r'^newstatus', views.add_status, name='add_status'),
    url(r'$', login_required(views.log), name="log")
]

log/models.py
from django.db import models
from django import forms


class LogCommentForm(forms.Form):
    redirect_url = forms.CharField(max_length=200)
    log_id = forms.CharField(max_length=100)
    content = forms.CharField(max_length=5000, required=False)
    close_issue = forms.BooleanField(required=False)


class LogEntryForm(forms.Form):
    message = forms.CharField(max_length=100000)
    run_name = forms.CharField(max_length=200, initial="none", required=False)
    detector = forms.CharField(max_length=200, initial="none", required=False)
    redirect = forms.CharField(max_length=200, initial="", required=False)

PRIORITY_CHOICES = (    
    (-2, "Default"),
    (-1, "All"),
    (0, "User Messages"),
    (1, "Info"),
    (2, "Warnings"),
    (3, "Errors"),
    (4, "Fatal"),
    (7, "Closed Warnings"),
    (8, "Closed Errors"),
    (9, "Closed Fatal Errors"),
    (10, "Slow Control Alarms"),
    (99, "Debug Output"),
    (-2, "Open issues"),
)


class LogSearchForm(forms.Form):
    detector = forms.CharField(label="Detector", max_length=100, required=False)
    run_name = forms.CharField(label="Run Name", max_length=200, required=False)
    start_date = forms.DateField(required=False, label="Start Date", widget=forms.DateInput)
    end_date = forms.DateField(required=False, label="End Date", widget=forms.DateInput)
    priority = forms.ChoiceField(choices=PRIORITY_CHOICES, label="Type filter", widget=forms.Select,
                                 required=False)
    user = forms.CharField(label="User", max_length=100, required=False)
    custom = forms.CharField(label="MongoDB Query", max_length=1000, required=False)
    max_entries = forms.IntegerField(required=False)

runs/models.py
from django.db import models
from django import forms

class RunCommentForm(forms.Form):
    run_id = forms.CharField(max_length=100)
    content = forms.CharField(max_length=5000, required=False)

class run_comment(forms.Form):
    text = forms.CharField(max_length=5000)

class run_search_form( forms.Form ):

    def __init__(self, list, *args, **kwargs):
        super( run_search_form, self).__init__(*args, **kwargs)
        self.fields['mode'] = forms.ChoiceField( choices=list, required=False )

    detectors = [ ("tpc", "TPC"), ("muon_veto", "Muon Veto"), ("all", "All")]
    detector = forms.ChoiceField(choices=detectors, required=False, label="Detector")
    startdate = forms.DateField(required = False, label = "Start Date", widget=forms.DateInput)
    enddate   = forms.DateField(required = False, label = "End Date", widget=forms.DateInput)
    GoodRuns  = forms.BooleanField(label = "Only good runs", required=False)
    custom = forms.CharField( max_length=1000, required = False )

log/views.py
from django.http import HttpResponsePermanentRedirect, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import datetime
import pytz
import json
from pymongo import MongoClient
from bson.objectid import ObjectId
from log.models import LogEntryForm, LogSearchForm, LogCommentForm
from bson.json_util import dumps
from django.conf import settings

def add_status(request):
    if request.method != "POST":
        return HttpResponse({}, content_type="application/json")

    new_form = LogEntryForm(request.POST)
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]
    mongo_collection = d['log']

    if new_form.is_valid():
        new_entry = {
            "message": new_form.cleaned_data['message'],
            "priority": 60,
            "sender": request.user.username,
            "time": pytz.utc.localize(datetime.datetime.now()),
            "run": new_form.cleaned_data['run_name'],
            "detector": new_form.cleaned_data['detector'],
            "tags": get_hash_tags(new_form.cleaned_data['message']),
        }
        mongo_collection.insert(new_entry)
    return HttpResponsePermanentRedirect("/")

def get_status(request):
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]
    mongo_collection = d['log']
    doc = mongo_collection.find({"priority": 60}).sort("time", -1).limit(1)[0]
    if doc is None:
        doc = {"message": "", "sender": "", "time": ""}
    return HttpResponse(dumps(doc), content_type="application/json")


def is_not_ro(user):
    if user.groups.filter(name='read_only').exists():
        return False
    return True

@login_required
def get_dispatcher_log(request):

    """
    Make the dispatcher log page
    """
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]

    mongo_collection = d['log']
    
    mongo_query = {"priority": {"$in": [0, 2, 3, 4, 7, 8, 9, 10]}}
    log_list = mongo_collection.find(mongo_query).sort("_id", -1)[:20]

    return HttpResponse(dumps(log_list), content_type="application/json")


@login_required
def log(request):

    """
    Make the main log page
    """
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]

    mongo_collection = d['log']
   
    mongo_query = {}

    # Set a default value for max entries
    max_entries = 100000

    if request.method == "GET":

        search_form = LogSearchForm(request.GET)

        if search_form.is_valid():

            # Strip the data
            if search_form.cleaned_data['custom'] != "":
                mongo_query = json.loads(search_form.cleaned_data['custom'])
            if search_form.cleaned_data['detector'] != "":
                mongo_query['detector'] = search_form.cleaned_data['detector']
            if search_form.cleaned_data['run_name'] != "":
                mongo_query['run'] = search_form.cleaned_data['run_name']
            if ( search_form.cleaned_data['priority'] == "" or 
                 search_form.cleaned_data['priority'] == -3 ):
                mongo_query['priority'] = {"$in": [0, 2, 3, 4, 7, 8, 9, 10]}
            elif search_form.cleaned_data['priority'] != '-1':

                if search_form.cleaned_data['priority'] == '-2':
                    mongo_query['priority'] = {"$gt": 1, "$lt": 5}
                else:
                    mongo_query['priority'] = int(search_form.cleaned_data['priority'])
            if search_form.cleaned_data['start_date'] is not None:
                mongo_query['date'] = {"$gt": datetime.datetime.combine(
                    search_form.cleaned_data['start_date'],
                    datetime.datetime.min.time())}
            if search_form.cleaned_data['end_date'] is not None:
                if 'date' in mongo_query.keys():
                    mongo_query['date']['$lt'] = datetime.datetime.combine(search_form.cleaned_data['end_date'],
                                                                           datetime.datetime.max.time())
                else:
                    mongo_query['time'] = {"$lt": datetime.datetime.combine(search_form.cleaned_data['end_date'],
                                                                            datetime.datetime.max.time())}
            if search_form.cleaned_data['max_entries'] is not None:
                max_entries = search_form.cleaned_data['max_entries']
    else:
        search_form = LogSearchForm()

    print(mongo_query)
    log_list = dumps(mongo_collection.find(mongo_query).sort("_id", -1)[:max_entries])

    return render(request, 'log/log.html', {"log_list": log_list, "form": search_form})


def get_hash_tags(text):
    # Takes in a text block and returns a list of hash tags
    return [tag.strip("#") for tag in text.split() if tag.startswith("#")]

@login_required
def new_comment(request):

    """
    Add a new comment to a log entry.
    """
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]

    mongo_collection = d['log']

    if request.method == 'POST' and is_not_ro(request.user):

        comment = LogCommentForm(request.POST)
        if comment.is_valid():
            
            # Get data
            redirect_url = comment.cleaned_data['redirect_url']
            doc_id = comment.cleaned_data['log_id']
            user = request.user.username
            date = pytz.utc.localize(datetime.datetime.now())

            # First close the issue if it's an issue closing request
            if "close_issue" in comment.cleaned_data and comment.cleaned_data['close_issue'] == True:
                mongo_collection.update({"_id": ObjectId(doc_id)}, 
                                        {"$inc": {"priority": 5},
                                         "$set": {"closed_user": user},
                                         "$set": {"closed_date": date}})

            # Now do the update to a comment if there is one
            if 'content' in comment.cleaned_data:
                text = comment.cleaned_data['content']
                user = request.user.username

                # If the entry exists append the comment to it
                comment_dict = {
                    "text": text,
                    "date": date,
                    "user":  user,
                    "tags": get_hash_tags(text),
                    "priority": 0
                    }

                mongo_collection.update({"_id": ObjectId(doc_id)}, {"$push": {"comments": comment_dict}})

            return HttpResponsePermanentRedirect(redirect_url)
    return HttpResponsePermanentRedirect('/log/')


@login_required(login_url="/login/")
def new_log_entry(request):

    redirect_url = "/log/"
    c = MongoClient(settings.LOG_DB_ADDR)
    d = c[settings.LOG_DB_NAME]

    mongo_collection = d['log']

    if request.method == 'POST' and is_not_ro(request.user):

        # Pull data from POST request form
        new_form = LogEntryForm(request.POST)

        if new_form.is_valid():
            new_entry = {
                "message": new_form.cleaned_data['message'],
                "priority": 0,
                "sender": request.user.username,
                "time": pytz.utc.localize(datetime.datetime.now()),
                "run": new_form.cleaned_data['run_name'],
                "detector": new_form.cleaned_data['detector'],
                "tags": get_hash_tags(new_form.cleaned_data['message']),
            }
            if new_form.cleaned_data['redirect'] != "":
                redirect_url = new_form.cleaned_data['redirect']

            mongo_collection.insert(new_entry)
        if redirect_url != "none":
            return HttpResponsePermanentRedirect(redirect_url)
        else:
            return HttpResponse("good")
    else:
        new_form = LogEntryForm()
    if redirect_url != 'none':
        return HttpResponsePermanentRedirect(redirect_url)
    return HttpResponse("good")

    #return render(request, 'log/newlogentry.html', {'form': new_form})

log/templates/log/log.html
{% extends "base.html" %}
{% block title %}Logbook{% endblock %}
{% load staticfiles %}
{% load log_extras %}
{% block content %}
<script src="{% static "jquery-ui-1.11.1/jquery-ui.js"%}"></script>
<script src="{% static "js/summernote.min.js"%}"></script>
<script src="{% static "js/Ply.min.js" %}" type="text/javascript"></script>
<link href="{% static "jquery-ui-1.11.1/jquery-ui.css" %}" rel="stylesheet">
<link href="{% static "emo/css/emo_logstyle.css" %}" rel="stylesheet">

<link href="{% static "css/summernote.css" %}" rel="stylesheet">
<script src="{% static "js/summernote.min.js" %}" type="text/javascript"></script>
<!--<script src="{% static "DataTables-1.10.7/media/js/jquery.dataTables.min.js"%}"></script>
<link href="{% static "DataTables-1.10.7/media/css/jquery.dataTables.min.css"%}" rel="stylesheet" />-->
<!-- Quill for markup -->
<link href="{% static "quill/quill.snow.css" %}" rel="stylesheet">
<script src="{% static "quill/quill.min.js" %}" type="text/javascript"></script>


<script src="{% static "DataTables-1.10.9/media/js/jquery.dataTables.min.js"%}"></script>
<script src="{% static "DataTables-1.10.9/media/js/dataTables.bootstrap.min.js"%}"></script>
<link href="{% static "DataTables-1.10.9/media/css/dataTables.bootstrap.min.css"%}" rel="stylesheet" />
<link href="{% static "css/ply.css" %}" rel="stylesheet">


  <script type="text/javascript">
    $(function() {
	$( "#id_startdate" ).datepicker({
	    changeMonth: true,
	    changeYear: true
	});
    });
  $(function() {
      $( "#id_enddate" ).datepicker({
	  changeMonth: true,
	  changeYear: true
      });
  });
  </script>

<style type="text/css">
    #id_start_date, #id_end_date, #id_priority, #id_custom, #id_user, #id_detector, #id_run_name{
        height: 20px;
        width: 70%;
        margin-top:10px;
    }
    #t_user{
       background-color:blue;
       color:white;
    }
    #t_warning{
       background-color: yellow;
    }
    #t_error{
       background-color: red;
       color: white;
    }
    td.details-control {
     background: url('{%static "img/details_open.png" %}') no-repeat center center;
     background-color: white;
     cursor: pointer;
    }
    tr.shown td.details-control {
       background: url('{%static "img/details_close.png" %}') no-repeat center center;
       background-color: white;
       cursor: pointer;
    }
</style>

<div class="col-xs-12 emo-search-bar">
    <form method="GET" action="/log/">
        <div class="row">
            <div class="col-sm-1" style="line-height:40px;"><strong>Filter:</strong></div>
            <div class="col-sm-2">From: {{form.start_date}} </div>
            <div class="col-sm-2">To: {{form.end_date}} </div>
            <div class="col-sm-2">Priority: {{ form.priority }}</div>
            <div class="col-sm-2">User: {{ form.user }}</div>
            <div class="col-sm-3">Run: {{ form.run_name }}</div>
        </div>
        <div class="row">
            <div class="col-sm-3 col-sm-offset-1">Detector: {{  form.detector }}</div>
            <div class="col-sm-5">MongoDB Query: {{ form.custom }} </div>
            <div class="col-sm-2 col-sm-offset-1">
                <button class="btn btn-info btn-sm" style="margin:8px;" type="submit" name="submit" style="height:30%;">Filter</button>
            </div>
        </div>
    </form>
</div>

<div class="row" style="margin-top:110px;">
  <div class="col-xs-3 col-sm-3">
    <!--<h3>DAQ Logbook</h3>-->
  </div>
  <div class="col-xs-1 col-sm-1 col-xs-offset-8" style="padding-right:10px">
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#logModal">+ New Entry</button>
  </div>
</div>

<table class="table emo-disjointed-table" id="logtable" width="100%"> 
  <thead class="emo-disjointed-table-head">
    <tr>
      <th>Expand</th>
      <th> Time (UTC)</th>
      <th> Sender </th>
      <th> Message </th>
      <th>Comments</th>
      <th>Flag</th>
    </tr>
  </thead>
  <tbody class="emo-disjointed-table-body">
    <tr class="emo-disjointed-table-row">
      <td style="width:10px" class="details-control"></td>
      <td style="color:black;"></td>
      <td style="color:black;"></td>
      <td style="color:black;"></td>
      <td style="pull-right"> <span class="glyphicon glyphicon-comment">&nbsp</span></td>
      <td></td>
    </tr>
  </tbody>
</table>


<!-- New Entry Modal -->
<div id="logModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Log Entry</h4>
      </div>
      <div class="modal-body">
        <form id='new_comment_form' action='/log/new_log_entry' method='post'>
	  {% csrf_token %}
	  <textarea type='text' id='new_comment_text' name='message' 
		    class='form-control'  placeholder='New comment...' 
		    style='width:80%;height:70%'>New comment...</textarea><hr> 
          <input class='btn btn-info btn-lg' type=submit value='New comment'/>
	</form>
      </div>
    </div>    
  </div>
</div>

<script>
function format ( d ) {
    // `d` is the original data object for the row
    var ret =
   '<div class="slider" style="background-color:#eeeeee;padding-left:0;padding-right:0;"><table cellpadding="5" cellspacing="0" border="0" style="background-color:white;width:100%;margin-bottom:10px;">';
 
      if(d.comments != null){
      for( x=0; x<d.comments.length; x+=1){
          var m = new Date(d.comments[x].date['$date']);
             var dateString = m.getUTCFullYear() +
                 "/"+ ("0"+(m.getUTCMonth()+1)).slice(-2) +"/"+ 
				     ("0"+m.getUTCDate()).slice(-2) + " " +
                ("0"+m.getUTCHours()).slice(-2) + ":" + 
				     ("0"+m.getUTCMinutes()).slice(-2) + ":" + 
				     ("0"+m.getUTCSeconds()).slice(-2);
			console.log(m);

        ret += '<tr style="border-width:1px;border-color:#999999;border-style:solid;border-left:0;border-right:0;">'+
          '<td valign="top" style="width:15%;padding:5px;">'+dateString+'</td>'+
          '<td valign="top" style="width:10%;padding:5px;"><stong>'+d.comments[x].user+'</strong></td>'+
          '<td style="min-width:60%;background-color:white;padding:5px;" class="hashes">'+ d.comments[x].text+ '</td>'+
        '</tr>';
     }}
ret += '</table>';
     console.log(d);
     ret += "<form onsubmit='if(!OKtoSubmit) event.preventDefault();' id='comment_form' action='/log/new_comment/' style='width:100%;' method='post'>" +
				     "{% csrf_token %}" +     
            '<textarea id="' + d._id['$oid'] + '_formtext" name="content" placeholder="New threaded comment..." style="width:100%;border-left:0;border-right:0">New threaded comment...</textarea>' +  
             '<br>' +                                                            
             '<input style="margin-top:10px;" type="hidden" name="redirect_url" value="{{ request.get_full_path }}"/>' +  
             '<button class="btn btn-info" type="submit" value="' + d._id['$oid'] + '" name="log_id" style="margin-bottom:15px;margin-left:15px" onclick="SubmitComment()">New comment</button>' + 
		'<input type="hidden" name="log_id" value="' + d._id['$oid'] + '"/>';
     if(d.priority == 2 || d.priority ==3 || d.priority ==4 ){
		ret += '&nbsp;<button class="btn btn-warning" onclick="ConfirmClose()">Submit and Close Issue</button>';
            ret += '&nbsp;<input class="hidden" type="checkbox" name="close_issue" onclick="ConfirmClose()"></input>';
     }
      ret +=  '</form></div>';

     return ret;
}
var OKtoSubmit = false;
function SubmitComment(){
	OKtoSubmit=true;
	$("#comment_form").submit();
        OKtoSubmit=false;

}
function ConfirmClose(){

Ply.dialog("confirm", "You're closing this alert. This means you understand what the alert means and know the problem has now been solved. You may confirm this by clicking OK. If you need help please contact the DAQ group.")
    .done(function(ui){ 
$("[name=close_issue]").attr("checked", true); 
SubmitComment();
$("[name=close_issue]").attr("checked", false);

});

}
function toHashtagUrl(hashtag) {
return "#";
//  return "http://myservice.com?q=" + hashtag;
}


$(document).ready(function(){

 $("#new_comment_text").summernote({height:200,
toolbar: [
    // [groupName, [list of button]]
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['font', ['strikethrough', 'superscript', 'subscript']],
    ['fontsize', ['fontsize']],
    ['color', ['color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['height', ['height']],
    ['insert', ['table', 'hr']]
  ],
                        "disableDragAndDrop": true,
});

   var thedata = {{ log_list|safe }};
	var table = $('#logtable').DataTable({
	  "data": thedata,
 "drawCallback": function( settings ) {
$(".hashes").linkify(toHashtagUrl);

    },
"fnRowCallback": function( nRow, aData, iDisplayIndex ) {
  nRow.className += " emo-disjointed-table-row";
  return nRow;
},
          "columns": [
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            { "data": "time", "width": "15%", "render": function (data) {
	      var m = new Date(data['$date']);
	     var dateString = m.getUTCFullYear() +
		 "/"+ (m.getUTCMonth()+1) +"/"+ m.getUTCDate() + " " + 
		m.getUTCHours() + ":" + m.getUTCMinutes() + ":" + m.getUTCSeconds();
	     return dateString;
    } },
            { "data": "sender", "render": function(data){
                  return "<strong>"+data+"</strong>"; }},
            { "data": "message", "width": "60%", className: "hashes" },
            { "data": "comments", "render":function(data){if(data==null) return 0; return data.length} },
            { "data": "priority",
              "render": function(data){
                  if(data==1)
		    return "info";
                  else if(data == 0)
                    return "user";
                  else if(data==2)
                    return "open warning";
                  else if(data==7)
                    return "closed warning";
                  else if(data == 3)
                    return "open error";
		  else if(data==8)
	            return "closed error";
                  else if(data == 4)
                    return "open fatal";
                  else if(data==9)
                    return "closed fatal";
                  else if(data==5)		 
                    return "command";
                  else if(data==10)
                    return "SC alarm";
                  else { console.log(data); return "";}
          }},],
          
          "order": [[ 1, "desc" ]],
          "iDisplayLength": 50,
          "createdRow": function ( row, data, index ) {				  
            $('td', row).eq(5).css('font-weight', 'bold');
            if ( data['priority'] == 2 || data['priority']==7) {
                $('td', row).eq(5).css('background-color', '#ffd800');
            }
            else if(data['priority'] == 10){
                 $('td', row).eq(5).css('background-color', '#ff6600');
                $('td', row).eq(5).css('color', 'white');
            }
            else if(data['priority'] == 3 || data['priority']==4 || data['priority'] == 8 || data['priority']==9){
                $('td', row).eq(5).css('background-color', '#e86850');
                $('td', row).eq(5).css('color', 'white');
            }
            else if(data['priority'] == 0){
                $('td', row).eq(5).css('background-color', '#587498');
                $('td', row).eq(5).css('color', 'white');

            }
            else if(data['priority'] == 5){
                $('td', row).eq(5).css('background-color', '#587058');
                $('td', row).eq(5).css('color', 'white');
            }
        }
     });

 // Add event listener for opening and closing details
    $('#logtable tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );
 
        if ( row.child.isShown() ) {
            // This row is already open - close it
            $('div.slider', row.child()).slideUp( function () {
               row.child.hide();
               tr.removeClass('shown');
            });
        }
        else {
            // Open this row

            row.child( format(row.data()), 'no-padding'  ).show();
	    tr.addClass('shown', 250, 'linear', 
            function(){
                 $("#"+row.data()['_id']['$oid']+"_formtext").summernote({
                     "height": 150,
			"disableDragAndDrop": true,
		      toolbar: [
                      
                         ['style', ['bold', 'italic', 'underline', 'clear']],
                         ['font', ['strikethrough', 'superscript', 'subscript']],
                         ['fontsize', ['fontsize']],
                         ['color', ['color']],
                         ['para', ['ul', 'ol', 'paragraph']],
                         ['height', ['height']],
                         ['insert', ['table', 'hr']]
                      ]

                 });
                  console.log("BABA");
                  console.log(row.data()['_id']['$oid']);
               });
		$('div.slider', row.child()).slideDown();
        }
	$(".hashes").linkify(toHashtagUrl);

    } );
});








</script>




{% endblock %}